### ISSUE TITLE
Doesn't Lint

### ISSUE THREAD

**Issue by bobrocke** [AtomLinter/linter-scss-lint#45] opened 2015-06-03 00:03 UTC
I don't get any errors thrown, nor do I get any linting. I'm not even sure where to look, now. I used to get errors about not finding scss-lint, but those have cleared up.

How can I tell why no linting is happening to .scss files?

**Comment by podo** [comment] 2015-06-03 06:07
Same here. Seems started to happen after recent Atom update.

**Comment by polybuildr** [comment] 2015-06-03 09:52
+1

**Comment by bobrocke** [comment] 2015-06-03 15:39
OK, while troubleshooting another problem I found I have a /Users/bob/.rvm/gems/ruby-2.0.0-p247 that is a broken sym-link. When I re-pointed it to /Users/bob/.rvm/gems/ruby-2.0.0-p247@rails3, scss-lint began working.

Maybe you guys have that problem, too?

**Comment by aniss** [comment] 2015-06-05 10:24
XML formatter was deprecated from scss-lint that's why https://github.com/brigade/scss-lint/releases/tag/v0.39.0

**Comment by dsandstrom** [comment] 2015-06-10 22:06
> XML formatter was deprecated from scss-lint that's why https://github.com/brigade/scss-lint/releases/tag/v0.39.0

There's the [Checkstyle](https://github.com/Sweetchuck/scss_lint_reporter_checkstyle) formatter that returns XML, but it adds a gem depedency and didn't fix things for me.  It would be smarter to use the JSON formatter instead.

**Comment by FalkoJoseph** [comment] 2015-06-12 18:10
Yeah, scss-lint stopped working for me as well. Hope this gets fixed.

**Comment by bobrocke** [comment] 2015-06-14 17:44
Check this issue for something that fixed it for me: https://github.com/AtomLinter/linter-scss-lint/issues/39

**Comment by benschell** [comment] 2015-06-16 17:57
Just a +1 on this; using the latest version of scss-lint makes this package not work due to the change indicated by @aniss  . A workaround for now is to remove the old version (`gem uninstall scss_lint`) and install the older version (`gem install scss_lint -v 0.38.0`).

**Comment by dsandstrom** [comment] 2015-06-16 18:20
Thanks @benschell.  However, what got it working again, for me, was running `gem install scss-lint -v 0.38.0` (the dash version of the gem name).  The underscore version does not work.

Side note, I mentioned that the JSON formatter should be used instead.  There is an open PR that already fixes this.  @hd-deman Are you able to work on this package?

**Comment by FalkoJoseph** [comment] 2015-06-18 07:53
https://github.com/AtomLinter/linter-scss-lint/pull/42 works for me.

**Comment by brunowego** [comment] 2015-06-21 23:20
+1

**Comment by anguspiv** [comment] 2015-06-25 03:47
So I think I have a potential quickfix using the checkstyle plugin for scsslint, and also using a fix for the scss-lint binary path issue. Though, since there is no spec I am going to spend a day or two kicking the tires before submitting my pull request. But feel free to test my fork please [https://github.com/AtomLinter/linter-scss-lint]()

**Comment by dsandstrom** [comment] 2015-06-25 03:51
@anguspiv #42 doesn't work for you?  The checkstyle formatter will add a gem dependency, JSON is the way to go.

**Comment by anguspiv** [comment] 2015-06-25 15:11
Hmm, didn't notice #42 till now, I'll give that a try. I would agree JSON would be the way to go.

**Comment by iam4x** [comment] 2015-06-26 13:08
Is the new release with #42 is working for you guys?

**Comment by polybuildr** [comment] 2015-06-26 13:09
Isn't working for me right now, at least. :/ But I only tested it today, after getting the new release, so I don't know if I've done this right.

**Comment by sergejmueller** [comment] 2015-06-26 19:09
The 1.0.5 release is not working.

**Comment by calderas** [comment] 2015-06-26 21:09
Not working for me: 
```
"name": "linter-scss-lint",
"version": "1.0.5",
```

```
scss-lint 0.39.0
```

**Comment by dsandstrom** [comment] 2015-06-30 17:36
It wasn't working at first, it was showing one error on the the top of the page.  However, I was messing around with linter and gem versions and got it to work.  I'm not exactly sure what the fix was, but try:
```
gem uninstall scss-lint
gem uninstall scss_lint
gem install scss_lint
```

I'm using the latest linter and gem:

linter@1.1.0
linter-scss-lint@1.0.5
scss_lint (0.39.0)

**Comment by calderas** [comment] 2015-06-30 22:22
confirmed, that worked for me as well

```
gem uninstall scss-lint
gem uninstall scss_lint

gem install scss_lint
apm install linter
apm install linter-scss-lint
```

update .atom/config.cson
```
"linter-scss-lint":
  executablePath: "~/.rbenv/shims/scss-lint"
```

**Comment by davegomez** [comment] 2015-07-05 05:52
The @calderas is not working for me.

Does anyone gonna fix this?

**Comment by hd-deman** [comment] 2015-07-05 10:43
@davegomez try to run 
`which  scss-lint` 
and use result as executablePath in config.

**Comment by iam4x** [comment] 2015-07-05 16:52
@davegomez It's hard to fix an issue which we can't reproduce. Ruby has too many configurations possible (rvbenv, rvm, plain ruby) it differs with systems too.

**Comment by davegomez** [comment] 2015-07-05 21:14
The executable path is working, it doesn't matter if it takes it automatically or if you set the complete path manually. The issue is with the latest version of the linter since you can use an older version and it works fine.

I already try to read the code to see if I could figure it out, but I'm not a CoffeeScript and can't understand very well how the atom packages work.

By the way, the linter launch a message about an unknown error at line one, so I suspect it could be a file parsing error or something like that.

**Comment by quicoto** [comment] 2015-07-09 07:34
Running the latest version of the linter (1.0.5) and Atom (1.0.2)

It throws two errors:

“The linter binary 'scss-lint' cannot be found.
Linting has been halted. Please install the linter binary or disable the linter plugin depending on it. Make sure to reload Atom to detect changes”

“Failed to spawn command scss-lint. Make sure scss-lint is installed and on your PATH”

Thank you.

**Comment by Fequois** [comment] 2015-07-09 10:32
@quicoto That's not a bug, that's an error message. You can resolve your issue by installing the `scss_lint` gem, or if already installed, manually enter its path in the 'linter-scss-lint' config.

**Comment by steelbrain** [comment] 2015-07-26 13:26
Fixed by https://github.com/AtomLinter/linter-scss-lint/pull/58

**Closed by steelbrain** 2015-07-26 13:26 UTC
Labels: bug
