### ISSUE TITLE
LinterScssLint.Linter is deprecated.

### ISSUE THREAD

**Issue by mikestreety** [AtomLinter/linter-scss-lint#53] opened 2015-07-08 13:26 UTC
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
LinterScssLint.Linter (/Users/mike/.atom/packages/linter/lib/linter.coffee:60:4)
new LinterScssLint (/Users/mike/.atom/packages/linter-scss-lint/lib/linter-scss-lint.coffee:18:51)
Object.lint (/Users/mike/.atom/packages/linter/lib/legacy.coffee:61:21)
<unknown> (/Users/mike/.atom/packages/linter/lib/editor-linter.coffee:68:23)
<unknown> (/Users/mike/.atom/packages/linter/lib/editor-linter.coffee:67:24)
Set.forEach (native)
```

**Comment by joshmedeski** [comment] 2015-07-08 19:50
+1

**Comment by iam4x** [comment] 2015-07-08 21:33
dupe of #52

**Closed by iam4x** 2015-07-08 21:33 UTC

**Comment by fluse** [comment] 2015-07-20 10:35
+1
